module xram_v1_0_1 #(
parameter    C_CORE_NAME = "xram_0",
parameter    C_SIM_DEVICE = "VERSAL_CORE",
parameter    C_S_AXI_XRAM0_DATA_WIDTH = 256,
parameter    C_S_AXI_XRAM1_DATA_WIDTH = 256,
parameter    C_S_AXI_XRAM2_DATA_WIDTH = 256,
parameter    C_S_AXI_LITE_XRAM_DATA_WIDTH = 32,

parameter    C_MEM_FREQ = 600,
parameter    C_PL_INTERFACE_0_FREQUENCY = 0,
parameter    C_PL_INTERFACE_0_INTERFACE_USAGE = 0,
parameter    C_PL_INTERFACE_1_FREQUENCY = 0,
parameter    C_PL_INTERFACE_1_INTERFACE_USAGE = 0,
parameter    C_PL_INTERFACE_2_FREQUENCY = 0,
parameter    C_PL_INTERFACE_2_INTERFACE_USAGE = 0
)
(
output wire      ifplxramaxi0arready,
output wire      ifplxramaxi0awready,
output wire   [15:0]   ifplxramaxi0bid,
output wire   [1:0]   ifplxramaxi0bresp,
output wire   [0:0]   ifplxramaxi0buser,
output wire      ifplxramaxi0bvalid,
output wire   [C_S_AXI_XRAM0_DATA_WIDTH-1:0]   ifplxramaxi0rdata,
output wire   [15:0]   ifplxramaxi0rid,
output wire   [0:0]   ifplxramaxi0rlast,
output wire   [1:0]   ifplxramaxi0rresp,
output wire   [31:0]   ifplxramaxi0ruser,
output wire      ifplxramaxi0rvalid,
output wire      ifplxramaxi0wready,
output wire      ifplxramaxi1arready,
output wire      ifplxramaxi1awready,
output wire   [15:0]   ifplxramaxi1bid,
output wire   [1:0]   ifplxramaxi1bresp,
output wire   [0:0]   ifplxramaxi1buser,
output wire      ifplxramaxi1bvalid,
output wire   [C_S_AXI_XRAM1_DATA_WIDTH-1:0]   ifplxramaxi1rdata,
output wire   [15:0]   ifplxramaxi1rid,
output wire   [0:0]   ifplxramaxi1rlast,
output wire   [1:0]   ifplxramaxi1rresp,
output wire   [31:0]   ifplxramaxi1ruser,
output wire      ifplxramaxi1rvalid,
output wire      ifplxramaxi1wready,
output wire      ifplxramaxi2arready,
output wire      ifplxramaxi2awready,
output wire   [15:0]   ifplxramaxi2bid,
output wire   [1:0]   ifplxramaxi2bresp,
output wire   [0:0]   ifplxramaxi2buser,
output wire      ifplxramaxi2bvalid,
output wire   [C_S_AXI_XRAM2_DATA_WIDTH-1:0]   ifplxramaxi2rdata,
output wire   [15:0]   ifplxramaxi2rid,
output wire   [0:0]   ifplxramaxi2rlast,
output wire   [1:0]   ifplxramaxi2rresp,
output wire   [31:0]   ifplxramaxi2ruser,
output wire      ifplxramaxi2rvalid,
output wire      ifplxramaxi2wready,
output wire      ifplxramaxiarready,
output wire      ifplxramaxiawready,
output wire   [1:0]   ifplxramaxibresp,
output wire      ifplxramaxibvalid,
output wire   [C_S_AXI_LITE_XRAM_DATA_WIDTH-1:0]   ifplxramaxirdata,
output wire   [1:0]   ifplxramaxirresp,
output wire      ifplxramaxirvalid,
output wire      ifplxramaxiwready,
output wire      xramplcorrerr,
output wire   [127:0]   xramplerrstatus,
output wire      xrampluncorrerr,
input wire   [63:0]   ifplxramaxi0araddr,
input wire   [1:0]   ifplxramaxi0arburst,
input wire   [3:0]   ifplxramaxi0arcache,
input wire   [15:0]   ifplxramaxi0arid,
input wire   [7:0]   ifplxramaxi0arlen,
input wire   [0:0]   ifplxramaxi0arlock,
input wire   [2:0]   ifplxramaxi0arprot,
input wire   [3:0]   ifplxramaxi0arqos,
input wire   [3:0]   ifplxramaxi0arregion,
input wire   [2:0]   ifplxramaxi0arsize,
input wire   [15:0]   ifplxramaxi0aruser,
input wire      ifplxramaxi0arvalid,
input wire   [63:0]   ifplxramaxi0awaddr,
input wire   [1:0]   ifplxramaxi0awburst,
input wire   [3:0]   ifplxramaxi0awcache,
input wire   [15:0]   ifplxramaxi0awid,
input wire   [7:0]   ifplxramaxi0awlen,
input wire   [0:0]   ifplxramaxi0awlock,
input wire   [2:0]   ifplxramaxi0awprot,
input wire   [3:0]   ifplxramaxi0awqos,
input wire   [3:0]   ifplxramaxi0awregion,
input wire   [2:0]   ifplxramaxi0awsize,
input wire   [15:0]   ifplxramaxi0awuser,
input wire      ifplxramaxi0awvalid,
input wire      ifplxramaxi0bready,
input wire      ifplxramaxi0rready,
input wire   [C_S_AXI_XRAM0_DATA_WIDTH-1:0]   ifplxramaxi0wdata,
input wire   [15:0]   ifplxramaxi0wid,
input wire   [0:0]   ifplxramaxi0wlast,
input wire   [((C_S_AXI_XRAM0_DATA_WIDTH/8)-1):0]   ifplxramaxi0wstrb,
input wire   [31:0]   ifplxramaxi0wuser,
input wire      ifplxramaxi0wvalid,
input wire   [63:0]   ifplxramaxi1araddr,
input wire   [1:0]   ifplxramaxi1arburst,
input wire   [3:0]   ifplxramaxi1arcache,
input wire   [15:0]   ifplxramaxi1arid,
input wire   [7:0]   ifplxramaxi1arlen,
input wire   [0:0]   ifplxramaxi1arlock,
input wire   [2:0]   ifplxramaxi1arprot,
input wire   [3:0]   ifplxramaxi1arqos,
input wire   [3:0]   ifplxramaxi1arregion,
input wire   [2:0]   ifplxramaxi1arsize,
input wire   [15:0]   ifplxramaxi1aruser,
input wire      ifplxramaxi1arvalid,
input wire   [63:0]   ifplxramaxi1awaddr,
input wire   [1:0]   ifplxramaxi1awburst,
input wire   [3:0]   ifplxramaxi1awcache,
input wire   [15:0]   ifplxramaxi1awid,
input wire   [7:0]   ifplxramaxi1awlen,
input wire   [0:0]   ifplxramaxi1awlock,
input wire   [2:0]   ifplxramaxi1awprot,
input wire   [3:0]   ifplxramaxi1awqos,
input wire   [3:0]   ifplxramaxi1awregion,
input wire   [2:0]   ifplxramaxi1awsize,
input wire   [15:0]   ifplxramaxi1awuser,
input wire      ifplxramaxi1awvalid,
input wire      ifplxramaxi1bready,
input wire      ifplxramaxi1rready,
input wire   [C_S_AXI_XRAM1_DATA_WIDTH-1:0]   ifplxramaxi1wdata,
input wire   [15:0]   ifplxramaxi1wid,
input wire   [0:0]   ifplxramaxi1wlast,
input wire   [((C_S_AXI_XRAM1_DATA_WIDTH/8)-1):0]   ifplxramaxi1wstrb,
input wire   [31:0]   ifplxramaxi1wuser,
input wire      ifplxramaxi1wvalid,
input wire   [63:0]   ifplxramaxi2araddr,
input wire   [1:0]   ifplxramaxi2arburst,
input wire   [3:0]   ifplxramaxi2arcache,
input wire   [15:0]   ifplxramaxi2arid,
input wire   [7:0]   ifplxramaxi2arlen,
input wire   [0:0]   ifplxramaxi2arlock,
input wire   [2:0]   ifplxramaxi2arprot,
input wire   [3:0]   ifplxramaxi2arqos,
input wire   [3:0]   ifplxramaxi2arregion,
input wire   [2:0]   ifplxramaxi2arsize,
input wire   [15:0]   ifplxramaxi2aruser,
input wire      ifplxramaxi2arvalid,
input wire   [63:0]   ifplxramaxi2awaddr,
input wire   [1:0]   ifplxramaxi2awburst,
input wire   [3:0]   ifplxramaxi2awcache,
input wire   [15:0]   ifplxramaxi2awid,
input wire   [7:0]   ifplxramaxi2awlen,
input wire   [0:0]   ifplxramaxi2awlock,
input wire   [2:0]   ifplxramaxi2awprot,
input wire   [3:0]   ifplxramaxi2awqos,
input wire   [3:0]   ifplxramaxi2awregion,
input wire   [2:0]   ifplxramaxi2awsize,
input wire   [15:0]   ifplxramaxi2awuser,
input wire      ifplxramaxi2awvalid,
input wire      ifplxramaxi2bready,
input wire      ifplxramaxi2rready,
input wire   [C_S_AXI_XRAM2_DATA_WIDTH-1:0]   ifplxramaxi2wdata,
input wire   [15:0]   ifplxramaxi2wid,
input wire   [0:0]   ifplxramaxi2wlast,
input wire   [((C_S_AXI_XRAM2_DATA_WIDTH/8)-1):0]   ifplxramaxi2wstrb,
input wire   [31:0]   ifplxramaxi2wuser,
input wire      ifplxramaxi2wvalid,
input wire   [31:0]   ifplxramaxiaraddr,
input wire   [2:0]   ifplxramaxiarprot,
input wire      ifplxramaxiarvalid,
input wire   [31:0]   ifplxramaxiawaddr,
input wire   [2:0]   ifplxramaxiawprot,
input wire      ifplxramaxiawvalid,
input wire      ifplxramaxibready,
input wire      ifplxramaxirready,
input wire   [C_S_AXI_LITE_XRAM_DATA_WIDTH-1:0]   ifplxramaxiwdata,
input wire   [((C_S_AXI_LITE_XRAM_DATA_WIDTH/8)-1):0]   ifplxramaxiwstrb,
input wire      ifplxramaxiwvalid,
input wire      s_axi_xram0_aclk,
input wire      s_axi_xram1_aclk,
input wire      s_axi_xram2_aclk,
input wire      s_axi_lite_xram_aclk,
input wire   [1:0]   plxramcssdtrign,
input wire      xram_main_clk,
input wire   [4:0]   plxramspare,
input wire      xram_sys_resetn,

output wire [31:0] ps_ocm2_apb_prdata,
output wire ps_ocm2_apb_pready,
output wire ps_ocm2_apb_pslverr,
output wire ps_ocm2_axi_arready,
output wire ps_ocm2_axi_awready,
output wire [15:0] ps_ocm2_axi_bid,
output wire [1:0] ps_ocm2_axi_bresp,
output wire [0:0] ps_ocm2_axi_buser,
output wire ps_ocm2_axi_bvalid,
output wire [127:0] ps_ocm2_axi_rdata,
output wire [15:0] ps_ocm2_axi_rid,
output wire [0:0] ps_ocm2_axi_rlast,
output wire [1:0] ps_ocm2_axi_rresp,
output wire [17:0] ps_ocm2_axi_ruser,
output wire ps_ocm2_axi_rvalid,
output wire ps_ocm2_axi_wready,
input wire [31:0] ps_ocm2_apb_paddr,
input wire ps_ocm2_apb_penable,
input wire [2:0] ps_ocm2_apb_pprot,
input wire ps_ocm2_apb_psel,
input wire [3:0] ps_ocm2_apb_pstrb,
input wire [31:0] ps_ocm2_apb_pwdata,
input wire ps_ocm2_apb_pwrite,
input wire [63:0] ps_ocm2_axi_araddr,
input wire [1:0] ps_ocm2_axi_arburst,
input wire [3:0] ps_ocm2_axi_arcache,
input wire [15:0] ps_ocm2_axi_arid,
input wire [7:0] ps_ocm2_axi_arlen,
input wire [0:0] ps_ocm2_axi_arlock,
input wire [2:0] ps_ocm2_axi_arprot,
input wire [3:0] ps_ocm2_axi_arqos,
input wire [3:0] ps_ocm2_axi_arregion,
input wire [2:0] ps_ocm2_axi_arsize,
input wire [15:0] ps_ocm2_axi_aruser,
input wire ps_ocm2_axi_arvalid,
input wire [63:0] ps_ocm2_axi_awaddr,
input wire [1:0] ps_ocm2_axi_awburst,
input wire [3:0] ps_ocm2_axi_awcache,
input wire [15:0] ps_ocm2_axi_awid,
input wire [7:0] ps_ocm2_axi_awlen,
input wire [0:0] ps_ocm2_axi_awlock,
input wire [2:0] ps_ocm2_axi_awprot,
input wire [3:0] ps_ocm2_axi_awqos,
input wire [3:0] ps_ocm2_axi_awregion,
input wire [2:0] ps_ocm2_axi_awsize,
input wire [15:0] ps_ocm2_axi_awuser,
input wire ps_ocm2_axi_awvalid,
input wire ps_ocm2_axi_bready,
input wire ps_ocm2_axi_rready,
input wire [127:0] ps_ocm2_axi_wdata,
input wire [15:0] ps_ocm2_axi_wid,
input wire [0:0] ps_ocm2_axi_wlast,
input wire [15:0] ps_ocm2_axi_wstrb,
input wire [17:0] ps_ocm2_axi_wuser,
input wire ps_ocm2_axi_wvalid,
input wire s_axi_xram3_aclk,
input wire lpd_lsbus_clk
);

localparam real   C_PL_INTERFACE_0_FREQUENCY_i = (C_PL_INTERFACE_0_FREQUENCY/1000000.0);
localparam real   C_PL_INTERFACE_1_FREQUENCY_i = (C_PL_INTERFACE_1_FREQUENCY/1000000.0);
localparam real   C_PL_INTERFACE_2_FREQUENCY_i = (C_PL_INTERFACE_2_FREQUENCY/1000000.0);
localparam real   C_MEM_FREQ_i = (C_MEM_FREQ/1.0);
localparam    C_PL_INTERFACE_0_INTERFACE_BANDWIDTH = ((C_PL_INTERFACE_0_FREQUENCY_i *(C_S_AXI_XRAM0_DATA_WIDTH/8)) * C_PL_INTERFACE_0_INTERFACE_USAGE);
localparam    C_PL_INTERFACE_0_NUM_MEM_BANKS = (4 * C_PL_INTERFACE_0_INTERFACE_USAGE);
localparam    C_PL_INTERFACE_1_INTERFACE_BANDWIDTH = ((C_PL_INTERFACE_1_FREQUENCY_i *(C_S_AXI_XRAM1_DATA_WIDTH/8))*C_PL_INTERFACE_1_INTERFACE_USAGE);
localparam    C_PL_INTERFACE_1_NUM_MEM_BANKS = (4*C_PL_INTERFACE_1_INTERFACE_USAGE);
localparam    C_PL_INTERFACE_2_INTERFACE_BANDWIDTH = ((C_PL_INTERFACE_2_FREQUENCY_i *(C_S_AXI_XRAM2_DATA_WIDTH/8))*C_PL_INTERFACE_2_INTERFACE_USAGE);
localparam    C_PL_INTERFACE_2_NUM_MEM_BANKS = (4 * C_PL_INTERFACE_2_INTERFACE_USAGE);
localparam    C_PS_INTERFACE_BANDWIDTH = (C_MEM_FREQ_i * (128/8));
localparam    C_PS_INTERFACE_NUM_MEM_BANKS = 4;
localparam    C_PS_INTERFACE_USAGE = 1;



 XRAM XRAM_inst(





.CPUR5AXICLK(s_axi_xram3_aclk),
.LPDLSBUSCLK(lpd_lsbus_clk),
.IFPSOCM2APBPRDATA  (ps_ocm2_apb_prdata  ),
.IFPSOCM2APBPREADY  (ps_ocm2_apb_pready  ),
.IFPSOCM2APBPSLVERR (ps_ocm2_apb_pslverr ),
.IFPSOCM2AXIARREADY (ps_ocm2_axi_arready ),
.IFPSOCM2AXIAWREADY (ps_ocm2_axi_awready ),
.IFPSOCM2AXIBID     (ps_ocm2_axi_bid     ),
.IFPSOCM2AXIBRESP   (ps_ocm2_axi_bresp   ),
.IFPSOCM2AXIBUSER   (ps_ocm2_axi_buser   ),
.IFPSOCM2AXIBVALID  (ps_ocm2_axi_bvalid  ),
.IFPSOCM2AXIRDATA   (ps_ocm2_axi_rdata   ),
.IFPSOCM2AXIRID     (ps_ocm2_axi_rid     ),
.IFPSOCM2AXIRLAST   (ps_ocm2_axi_rlast   ),
.IFPSOCM2AXIRRESP   (ps_ocm2_axi_rresp   ),
.IFPSOCM2AXIRUSER   (ps_ocm2_axi_ruser   ),
.IFPSOCM2AXIRVALID  (ps_ocm2_axi_rvalid  ),
.IFPSOCM2AXIWREADY  (ps_ocm2_axi_wready  ),
.IFPSOCM2APBPADDR   (ps_ocm2_apb_paddr   ),
.IFPSOCM2APBPENABLE (ps_ocm2_apb_penable ),
.IFPSOCM2APBPPROT   (ps_ocm2_apb_pprot   ),
.IFPSOCM2APBPSEL    (ps_ocm2_apb_psel    ),
.IFPSOCM2APBPSTRB   (ps_ocm2_apb_pstrb   ),
.IFPSOCM2APBPWDATA  (ps_ocm2_apb_pwdata  ),
.IFPSOCM2APBPWRITE  (ps_ocm2_apb_pwrite  ),
.IFPSOCM2AXIARADDR  (ps_ocm2_axi_araddr  ),
.IFPSOCM2AXIARBURST (ps_ocm2_axi_arburst ),
.IFPSOCM2AXIARCACHE (ps_ocm2_axi_arcache ),
.IFPSOCM2AXIARID    (ps_ocm2_axi_arid    ),
.IFPSOCM2AXIARLEN   (ps_ocm2_axi_arlen   ),
.IFPSOCM2AXIARLOCK  (ps_ocm2_axi_arlock  ),
.IFPSOCM2AXIARPROT  (ps_ocm2_axi_arprot  ),
.IFPSOCM2AXIARQOS   (ps_ocm2_axi_arqos   ),
.IFPSOCM2AXIARREGION(ps_ocm2_axi_arregion),
.IFPSOCM2AXIARSIZE  (ps_ocm2_axi_arsize  ),
.IFPSOCM2AXIARUSER  (ps_ocm2_axi_aruser  ),
.IFPSOCM2AXIARVALID (ps_ocm2_axi_arvalid ),
.IFPSOCM2AXIAWADDR  (ps_ocm2_axi_awaddr  ),
.IFPSOCM2AXIAWBURST (ps_ocm2_axi_awburst ),
.IFPSOCM2AXIAWCACHE (ps_ocm2_axi_awcache ),
.IFPSOCM2AXIAWID    (ps_ocm2_axi_awid    ),
.IFPSOCM2AXIAWLEN   (ps_ocm2_axi_awlen   ),
.IFPSOCM2AXIAWLOCK  (ps_ocm2_axi_awlock  ),
.IFPSOCM2AXIAWPROT  (ps_ocm2_axi_awprot  ),
.IFPSOCM2AXIAWQOS   (ps_ocm2_axi_awqos   ),
.IFPSOCM2AXIAWREGION(ps_ocm2_axi_awregion),
.IFPSOCM2AXIAWSIZE  (ps_ocm2_axi_awsize  ),
.IFPSOCM2AXIAWUSER  (ps_ocm2_axi_awuser  ),
.IFPSOCM2AXIAWVALID (ps_ocm2_axi_awvalid ),
.IFPSOCM2AXIBREADY  (ps_ocm2_axi_bready  ),
.IFPSOCM2AXIRREADY  (ps_ocm2_axi_rready  ),
.IFPSOCM2AXIWDATA   (ps_ocm2_axi_wdata   ),
.IFPSOCM2AXIWID     (ps_ocm2_axi_wid     ),
.IFPSOCM2AXIWLAST   (ps_ocm2_axi_wlast   ),
.IFPSOCM2AXIWSTRB   (ps_ocm2_axi_wstrb   ),
.IFPSOCM2AXIWUSER   (ps_ocm2_axi_wuser   ),
.IFPSOCM2AXIWVALID  (ps_ocm2_axi_wvalid  )
);

endmodule


