domain_path: J:\work\projects\versal\psHelloWorld\software\myhelloworld\export\myhelloworld\sw\standalone_psv_cortexa72_0
app_src_dir: C:\AMDDesignTools_EML\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
